Header provider - rebased
fcrepo4-exts/fcrepo4-vagrant pull request #95
Opened 2019-04-03 22:08 UTC by dbernstein

**This is @whikloj's PR (https://github.com/fcrepo4-exts/fcrepo4-vagrant/pull/92 - now closed) rebased and merged on my latest PR (https://github.com/fcrepo4-exts/fcrepo4-vagrant/pull/94).**
* * *
Once https://github.com/fcrepo4-exts/fcrepo4-vagrant/pull/94 has been merged,  I will merge this one.

Text of the original PR follows: 
***
**JIRA Ticket**: n/a

# What does this Pull Request do?
Installs a customized `fcrepo-config.xml` with the headerPrincipalProvider enabled.

# How should this be tested?

Need to stand up this vagrant, then create a resource and restrict it to one of the users (ie. adminuser). 

Then try to access that resource using the other user and the header
ie.
```
curl -i -u testuser:password1 -H"some-header: adminuser" http://localhost:8080/fcrepo/rest/your_restricted_resource
```
# Additional Notes:

Example:
* Does this change require documentation to be updated? yes, some information about the header might be helpful.
* Does this change add any new dependencies? no
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? no
* Could this change impact execution of existing code? no

# Interested parties
@fcrepo4/committers

2019-04-03 22:17 UTC, dbernstein commented
I have tested the header provider feature post rebase.  Everything works.  This PR is good to go barring any issues discovered by @yinlinchen on https://github.com/fcrepo4-exts/fcrepo4-vagrant/pull/94

2019-04-04 16:27 UTC, awoods requested changes

2019-04-04 16:27 UTC, awoods commented on README.md
> +### Fedora Configuration
This section is duplicated below.

2019-04-04 16:38 UTC, dbernstein commented on README.md
> +### Fedora Configuration
Fixed.

2019-04-04 16:38 UTC, dbernstein commented on README.md
> +### Fedora Configuration
Fixed.

2019-04-04 16:41 UTC, awoods approved these changes

2019-04-04 17:08 UTC, whikloj approved these changes

2019-04-04 18:05 UTC, merged